# Create a directory to extract the file to
- name: "create directory"
  file:
    path: ~/project/backend
    state: directory

- name: "extract file"
  unarchive:
    src: ~/project/artifact.tar.gz
    dest: ~/project/backend

- name: "start app"
  shell: |
    pwd
    ls -la
    cd backend
    pwd
    npm install
    pm2 stop default
    pm2 start npm -- start
