# Create a directory to extract the file to
- name: "create directory"
  file:
    path: ~/project/backend
    state: directory

- name: "install pm2"
  become: true
  npm:
    name: pm2
    global: yes
    production: yes
    state: present

#- name: "copy backend file"
#  become: true
#  copy:
#    src: /root/project/backend
#    dest: /root
#    force: no

- name: "extract file"
  unarchive:
    src: ~/project/artifact.tar.gz
    dest: ~/project/backend

- name: "install npm packages"
  become: true
  command: npm install
  args:
    chdir: ~/project/backend

- name: "compile npm packages"
  become: true
  command: npm run build
  args:
    chdir: ~/project/backend

- name: "start server"
  become: true
  command: pm2 start npm -- run start
  args:
    chdir: ~/project/backend/dist

#- name: "start app"
#  shell: |
#    pwd
#    ls -la
#    cd backend
#    pwd
#    npm install
#    npm run build
#    pm2 stop default
#    pm2 start npm -- start
