- name: "extract file"
  unarchive:
    src: ~/project/artifact.tar.gz
    dest: ./backend
- name: "start app"
  command: |
    cd backend
    npm install
    pm2 stop default
    pm2 start npm -- start
