- name: "create directory"
  file:
    path: /home/ubuntu/backend
    state: directory

- name: "unarchive backend files"
  unarchive:
    src: ~/project/artifact.tar.gz
    dest: /home/ubuntu/backend

# worked, but took a lot of time
#- name: "upgrade packages."
#  become: true
#  apt:
#    upgrade: "yes"7

# is working fine
#- name: "install dependencies."
#  become: true
#  apt:
#    name: ["nodejs", "npm"]
#    update_cache: yes

# is working fine
#- name: "install pm2"
#  become: true
#  npm:
#    name: pm2
#    global: yes
#    production: yes
#    state: present

# fails
#- name: "show files"
#  become: true
#  shell: | 
#    ls -la /root/project/backend

# always time out
#- name: "copy backend file"
#  become: true
#  copy:
#    src: /root/project/backend
#    dest: /root
#    force: no

#- name: "show files"
#  become: true
#  shell: | 
#    ls -la /root/backend
#    ls -la /root

- name: "install node_modules"
  become: true
  command: npm install
  args:
    chdir: /home/ubuntu/backend

- name: "build npm packages"
  become: true
  command: npm run build
  args:
    chdir: /home/ubuntu/backend

- name: "start server"
  become: true
  command: pm2 start npm -- run start
  args:
    chdir: /home/ubuntu/backend